---
title: "Stats 7 Homework 2^[Exercises adapted or copied from OpenIntro Statistics (4th edition) by David Diez, Mine Cetinkaya-Rundel, and Christopher D Barr https://www.openintro.org/book/os/ protected under the Creative Commons License https://creativecommons.org/licenses/by-sa/3.0/]"
output: pdf_document
date: "Due August 16 at 11:59 PM"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

*Make sure to write your answers in complete sentences.*

*Keep in mind the more work you show the more partial credit you can receive. If you only put the final answer and it is wrong, we do not know what you did to get there so we can't award partial credit.*


**Question 1**  
What percent of a standard normal distribution, $N(\mu = 0, \sigma = 1)$, is found in each region? For each: 

- sketch the distribution (i.e. draw the normal curve centered at the mean) and indicate what area we are looking for
- write out the `R` code you used to calculate the area
- calculate the percentage of the distribution that lies in that region

**(a)** Z > -1.13  

**(b)** Z < 0.18

**(c)** Z > 8

**(d)** |Z| < 0.5


**Question 2**

The distribution of passenger vehicle speeds traveling on the Interstate 5 Freeway (I-5) in California is nearly normal with a mean of 72.6 miles/hour and a standard deviation of 4.78 miles/hour.

**(a)** What percent of passenger vehicles travel slower than 80 miles/hour?

**(b)** What percent of passenger vehicles travel between 60 and 80 miles/hour?

**(c)** How fast do the fastest 5% of passenger vehicles travel?

**(d)** The speed limit on this stretch of the I-5 is 70 miles/hour. Approximate what percentage of the passenger
vehicles travel above the speed limit on this stretch of the I-5.

**Question 3**

Heights of 10 year olds, regardless of gender, closely follow a normal distribution with mean 55 inches and standard deviation 6 inches. The height requirement for Batman the Ride at Six Flags Magic Mountain is 54 inches. 

**(a)** What percent of 10 year olds cannot go on this ride?

**(b)** Say engineers were thinking of putting a limit on the maximum height of a passenger. If the limit was 6 feet (72 inches), what percent of 10 year olds would not be able to ride?


**Question 4**

For each of the following situations, state whether the parameter of interest is a mean or a proportion.

**(a)** A poll shows that 64% of Americans personally worry a great deal about federal spending and the budget
deficit.

**(b)** A survey reports that local TV news has shown a 17% increase in revenue within a two year period
while newspaper revenues decreased by 6.4% during this time period.

**(c)** In a survey, high school and college students are asked whether or not they use geolocation services on
their phones.

**(d)** In a survey, smart phone users are asked whether or not they use a web-based taxi service.

**(e)** In a survey, smart phone users are asked how many times they used a web-based taxi service over the
last year.


**Question 5**

In a random sample 765 adults in the United States, 322 say they could not cover a $400 unexpected expense without borrowing money or going into debt.

**(a)** What population is under consideration in the data set?

**(b)** What parameter is being estimated?

**(c)** What is the point estimate for the parameter?

**(d)** What is the name of the statistic we use to measure the uncertainty of the point estimate?

**(e)** Compute the value from part (d) for this context.

**(f)** A cable news pundit thinks the value is actually 50%. Should she be surprised by the data?

**(g)** Suppose the true population value was found to be 40%. If we use this proportion to recompute the
value in part (e) using p = 0.4 instead of $\hat{p}$, does the resulting value change much?


**Question 6**

Of all freshman at a large college, 16% made the dean’s list in the current year. As part of a class project, students randomly sample 40 students and check if those students made the list. They repeat this 1,000 times and build a distribution of sample proportions.

**(a)** What is this distribution called?

**(b)** Would you expect the shape of this distribution to be symmetric or skewed? Explain your reasoning.

**(c)** Calculate the variability of this distribution.

**(d)** Suppose the students decide to sample again, this time collecting 90 students per sample, and they again
collect 1,000 samples. They build a new distribution of sample proportions. How will the variability
of this new distribution compare to the variability of the distribution when each sample contained 40
observations?

**Question 7**

A poll conducted in 2013 found that 52% of U.S. adult Twitter users get at least some news on Twitter. The standard error for this estimate was 2.4%, and a normal distribution may be used to model the sample proportion. Construct a 99% confidence interval for the fraction of U.S. adult Twitter users who get some news on Twitter, and interpret the confidence interval in context.


**Question 8**

A poll conducted in 2013 found that 52% of U.S. adult Twitter users get at least some news on Twitter, and the standard error for this estimate was 2.4%. Identify each of the following statements as true or false. Provide an explanation to justify each of your answers.

**(a)** Since the standard error is 2.4%, we can conclude that 97.6% of all U.S. adult Twitter users were
included in the study.

**(b)** If we want to reduce the standard error of the estimate, we should collect less data.

**(c)** If we construct a 90% confidence interval for the percentage of U.S. adults Twitter users who get
some news through Twitter, this confidence interval will be wider than a corresponding 99% confidence
interval.


**Question 9**
A store randomly samples 603 shoppers over the course of a year and finds that 142 of them made their visit because of a coupon they’d received in the mail. 

**(a)** Construct a 95% confidence interval for the fraction of all shoppers during the year whose visit was because of a coupon they’d received in the mail. Remember to check the conditions required to use a normal distribution for our point estimate.

**(b)** What does "95% confident" mean? Explain in the context of the application.
