---
title: "Daily Schedule"
output: 
  html_document:
    css: "style.css"
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)

library(fontawesome)
```

## Before the first day of class 

- [`r fa("link", fill = "blue")`](https://catalinamedina.github.io/uci-stats7-su22-website/syllabus.html) Read the class syllabus 
- [`r fa("link", fill = "blue")`](https://www.r-project.org/) Install R (free software)
- [`r fa("link", fill = "blue")`](https://www.rstudio.com/) Install the free version of Rstudio 

## Monday Aug 1, 2022  

- Watch set 1 of lecture videos
    - [`r fa("video", fill = "blue")`](https://uci.zoom.us/rec/share/iEzan4P2GVBIK4rEa2LtOLH1fe9KaDx3zsovVnalo_mfIUoHGnZZulOkBsW-ZlTR.VXePD4F_vhRPVsgU?startTime=1659214374000) Introduction to the class video: 
    - [`r fa("video", fill = "blue")`](https://uci.zoom.us/rec/share/oD5hLVonR3CZ92t8D9zmJJF1qfLshfCnHsL0-_-qvOloMS1s3rohD9TMg32EfXyF.DBGfPottko6zeJyR?startTime=1659204319000) [`r fa("file", fill = "blue")`](lecture-slides/lecture1-section1.1-case-study.pdf) Section 1.1: Motivating case study 
    - [`r fa("video", fill = "blue")`](https://uci.zoom.us/rec/share/LfwhN6yTv7-nOE0cIAUx4vZoFyeK5joam7mQnOk6QGyZVGqF47625j9HUtJu2HWO.m9QSfwOlYGH0pzMb?startTime=1659218067000) [`r fa("file", fill = "blue")`](lecture-slides/lecture1-section1.2-data-basics.pdf) Section 1.2: Data basics
    - [`r fa("video", fill = "blue")`](https://uci.zoom.us/rec/share/8ez_7EOY5QoAxHlVcT-EffYubi-xg0R8Ebk7AiDHByWpaygZrSREJ0XFFuycelkr.ROp41PFoMRk7OaKo?startTime=1659226434000) [`r fa("file", fill = "blue")`](lecture-slides/lecture1-section1.3-sampling-principles-and-strategies.pdf) Section 1.3: Sampling principles and strategies 
    - [`r fa("video", fill = "blue")`](https://uci.zoom.us/rec/share/3KQRxWLSiqBHGxL6TG9mMrmhj90gxQfo3iLRe3pIFOfWBVLHaCSYZue-AtxKZNDj.zbn4J4xUTTzUJzq-?startTime=1659228286000) [`r fa("file", fill = "blue")`](lecture-slides/lecture1-section1.4-experiments.pdf) Section 1.4: Experiments 
- [`r fa("link", fill = "blue")`](https://canvas.eee.uci.edu/courses/46939/quizzes/233237) Complete lecture video quiz 1 on Canvas by 11:59 pm on August 2nd (3 attempts allowed for this quiz)

## Tuesday Aug 2, 2022

- [`r fa("file", fill = "blue")`](lecture-slides/lecture1-practice.pdf) (Google slides: [`r fa("link", fill = "blue")`](https://docs.google.com/presentation/d/1KnEApLH-6K-tYN2pbxHxl98iN705VoZKGVFfr-LeLQ4/edit?usp=sharing)) Meet in ICS 180 at 1pm for the first day of in person lecture 

## Wednesday Aug 3, 2022

- Meet in DBH 1500 at 4pm for discussion
    - [`r fa(name = "file", fill = "blue")`](discussion-material/stats7-discussion1-script.R) Discussion R script
    - [`r fa(name = "file", fill = "blue")`](discussion-material/starbucks.csv) Discussion Starbucks data
- Watch lecture 2 videos
    - [`r fa(name = "video", fill = "blue")`](https://uci.yuja.com/V/Video?v=5550088&node=24377207&a=655470973&autoplay=1) [`r fa("file", fill = "blue")`](lecture-slides/lecture2-section2.1-examining-numerical-data.pdf) Section 2.1 Examining numerical data
    - [`r fa(name = "video", fill = "blue")`](https://uci.zoom.us/rec/share/DkpYGufePoIj9VWIeM5GGgk216tEMvcaVuPtgilT3YCeBCDsBUOaO9XsWStzINc.QnpaVvA7Vz-j_sDO?startTime=1659505515000) [`r fa("file", fill = "blue")`](lecture-slides/lecture2-section2.2-considering-categorical-data.pdf) Section 2.2 Considering categorical data
- [`r fa(name = "link", fill = "blue")`](https://canvas.eee.uci.edu/courses/46939/quizzes/234632) Complete lecture video quiz 2 on Canvas by 11:59pm on August 3rd 

## Thursday Aug 4, 2022

- [`r fa("file", fill = "blue")`](lecture-slides/lecture2-practice.pdf) [`r fa("link", fill = "blue")`](https://docs.google.com/presentation/d/1zNV-M1LuDTg7sTJVo0oBZLPTP1FtwymeXsJrspX4hzg/edit?usp=sharing) Attend lecture at 1pm
- [`r fa("file", fill = "blue")`](homework/hw1/stats7-hw1.pdf) Homework 1 released. Due on August 9th at 11:59pm.

## Friday Aug 5, 2022

- TA office hour 3-4pm on Zoom (see Canvas for Zoom link)

## Monday Aug 8, 2022

- Instructor office hour 10-11 am on Zoom
- Watch lecture 3 videos
    - [`r fa(name = "video", fill = "blue")`](https://uci.zoom.us/rec/share/AuG3HClMhtYs30BTSez_kpVc0Nm7xQU7e0h9TQXDCZedFwzu2YirPc5NXL24-z6i._7YEnSkfoTPmWfX-?startTime=1659938147000) [`r fa("file", fill = "blue")`](lecture-slides/lecture3-section3.5-continuous-distributions.pdf) Section 3.5 Continuous distributions
    - [`r fa(name = "video", fill = "blue")`](https://uci.zoom.us/rec/share/f0ghKmQIbyiWni3yeuI1naNrzyJ_Hi8y6crXT8np9PNUp0zi51b6VuRU2uU9Q71_.2ms3JfeFlSyfw8BM?startTime=1659940349000) [`r fa("file", fill = "blue")`](lecture-slides/lecture3-section4.1-normal-distribution.pdf) Section 4.1 Normal distribution
- Take lecture video quiz 3 [`r fa(name = "link", fill = "blue")`](https://canvas.eee.uci.edu/courses/46939/quizzes/234934) due on Canvas at 11:59pm

## Tuesday Aug 9, 2022

- [`r fa("file", fill = "blue")`](lecture-slides/lecture3-practice.pdf) [`r fa(name = "link", fill = "blue")`](https://docs.google.com/presentation/d/1G-O8VvLUu8KDTFWndxztmn0j89DYdIwhdae-d-tO8xs/edit?usp=sharing) Attend lecture 3 at 1pm
- Homework 1 due on Gradescope at 11:59pm
    - [`r fa("file", fill = "blue")`](homework/hw1/stats7-hw1-solutions.pdf) Homework 1 solutions

## Wednesday Aug 10, 2022

- Attend discussion and take discussion quiz 1 in person
- Watch lecture 4 videos
    - [`r fa(name = "video", fill = "blue")`](https://uci.zoom.us/rec/share/NTsJFdVkBGwk_usiIppU-P94VhAjRgRy7JOE9kJa2UmDFRxPA7-NXSHcV19vTrFJ.3eN2J-7UheIHS-M1?startTime=1660109662000) [`r fa("file", fill = "blue")`](lecture-slides/lecture4-section5.1-point-estimates-and-sampling-variability.pdf) Section 5.1 Point estimates and sampling variability
    - [`r fa(name = "video", fill = "blue")`](https://uci.zoom.us/rec/share/DRNBMSghU9F8Shr-iwpfl5_qXQ5xbynse-ZovFBIGhn2F-_MMRLIJJD-T_qp0mNe.uYAKm21Nu2QeKWmu?startTime=1660111229000) [`r fa("file", fill = "blue")`](lecture-slides/lecture4-section5.2-confidence-intervals-for-proportions.pdf) Section 5.2 Confidence intervals for a proportion
    - [`r fa(name = "video", fill = "blue")`](https://uci.zoom.us/rec/share/HkdEDMf3juhNPkL_BfPPjlHFiNsCKXc9e1VFXXbW562AJIOBxF1ZAEshCp8qRtQe.HqCOpY52ukcuTP1B?startTime=1660114154000) [`r fa("file", fill = "blue")`](lecture-slides/lecture4-section2.3-case-study-gender-discrimination.pdf) Section 2.3 Introduction to the idea of hypothesis testing
- Take lecture video quiz 4 due on Canvas at 11:59pm

## Thursday Aug 11, 2022

- [`r fa("file", fill = "blue")`](lecture-slides/lecture4-practice.pdf) [`r fa("link", fill = "blue")`](https://docs.google.com/presentation/d/1junLo66xcBrBDM-ok4Dksex8ykORzLO0SRkCZlBbAh4/edit?usp=sharing) Attend lecture at 1pm
- [`r fa("file", fill = "blue")`](homework/hw2/stats7-hw2.pdf) Homework 2 released. Due August 16th at 11:59pm on Gradescope.

## Friday Aug 12, 2022

- TA office hour 3-4pm on Zoom (see Canvas for Zoom link)

## Monday Aug 15, 2022

- Instructor office hour 10-11am on Zoom
- Watch lecture 5 videos
    - [`r fa(name = "video", fill = "blue")`](https://uci.zoom.us/rec/share/jwfUhumiddxKq3aETpn7cGlb5B-Hr9eZ0stHS8itpJa46PKBV0rgkYNjPmETDA71.-brM_j9XeRnIsceq?startTime=1660545360000) [`r fa("file", fill = "blue")`](lecture-slides/lecture5-section5.3-hypothesis-testing-for-a-proportion.pdf) Section 5.3 Hypothesis testing for a proportion
    - [`r fa(name = "video", fill = "blue")`](https://uci.zoom.us/rec/share/qzo9DE0BYEDm7atUY52lEGrc6kS4MzFQm-7QaQQrAuBK8EWdTvCfkvrtmjBvLjA9.CnRQ_aFlMooVCjmQ?startTime=1660547721000) [`r fa("file", fill = "blue")`](lecture-slides/lecture5-section6.1-inference-for-a-single-proportion.pdf) Section 6.1 Inference for a single proportion
    - [`r fa(name = "video", fill = "blue")`](https://uci.zoom.us/rec/share/k6ayX4j7p_AOgcEyAg1sjQ-t-OE_TsvHxJO2ktUsNDDe6a_d9cqFYHfnnP4Ueyw6.Tde2KQa4bPXukv2c?startTime=1660549031000) [`r fa("file", fill = "blue")`](lecture-slides/lecture5-section6.2-difference-of-two-proportions.pdf) Section 6.2 Inference for two proportions
- Take lecture video quiz 5 due on Canvas Tuesday at noon

## Tuesday Aug 16, 2022

- Lecture video quiz 5 due at noon
- [`r fa("file", fill = "blue")`](lecture-slides/lecture5-practice.pdf) [`r fa("link", fill = "blue")`](https://docs.google.com/presentation/d/1hwDAFj4cnINySefrOrer1J-RBOhcxJCr8KoP49akmMA/edit?usp=sharing) Attend lecture at 1pm

## Wednesday Aug 17, 2022

- Discussion quiz 2 in discussion at 4pm
- Homework 2 due at 11:59pm on Gradescope
- Watch lecture 6 videos
    - [`r fa(name = "video", fill = "blue")`](https://uci.zoom.us/rec/share/k2kJ_uk5e-FAqAqDVzWm9jbDM_BolhJ-WwpdyW_k201dZP8E0P13sDEiz99C929n.uRmTodO7EhMRKZ6t?startTime=1660701095000) [`r fa("file", fill = "blue")`](lecture-slides/lecture6-section6.3-chi-square-test-of-gof.pdf) Section 6.3 Chi square test for goodness of fit
    - [`r fa(name = "video", fill = "blue")`](https://uci.zoom.us/rec/share/n9XqFIaNC2VZUWShW4Zc7LLDTuHe3Dl0xu-KR7NP7LFugoiovutdaanqSiI2iAMq.vAUKN0isAxbQdBoE?startTime=1660703627000) [`r fa("file", fill = "blue")`](lecture-slides/lecture6-section6.4-chi-square-test-of-independence.pdf) Section 6.4 Chi square test for independence
- Take lecture video quiz 6 due on Canvas Thursday at noon

## Thursday Aug 18, 2022

- [`r fa("file", fill = "blue")`](lecture-slides/lecture6-practice.pdf) [`r fa("link", fill = "blue")`](https://docs.google.com/presentation/d/1Vrpf7gDmEsmrqn5oLRGlqornJlxCUzkxIdqlwZF1QJg/edit?usp=sharing) Attend lecture at 1pm
- [`r fa("file", fill = "blue")`](homework/hw2/stats7-hw2-solutions.pdf) Review homework 2 solutions
- [`r fa("file", fill = "blue")`](homework/hw3/stats7-hw3.pdf) Homework 3 released. Due August 23rd at 11:59pm on Gradescope.

## Friday Aug 19, 2022

- TA office hour 3-4pm on Zoom (see Canvas for Zoom link)

## Monday Aug 22, 2022

- Watch lecture 7 videos
    - [`r fa(name = "video", fill = "blue")`](https://uci.zoom.us/rec/share/LKlfHQlm12isPvNBX6BXb06vG36zBqUd7P60krZfiEmVPtWcWLIp92RMyxNZXOs3.X0uvQKL247D0SwaQ?startTime=1661166346000) [`r fa("file", fill = "blue")`](lecture-slides/lecture7-section7.1-inference-for-a-mean.pdf) Section 7.1 Inference for a mean with one sample
    - [`r fa(name = "video", fill = "blue")`](https://uci.zoom.us/rec/share/gC_M6IE3GBB67Vfr4wVcKZd19IxUYKOOwFE-uf9IVYRQh7p3H3YU39pIfkdN5EG-.qRzBxRbcsmW5DEVu?startTime=1661167879000) [`r fa("file", fill = "blue")`](lecture-slides/lecture7-section7.2-paired-data.pdf) Section 7.2 Inference for a mean with paired data
    - [`r fa(name = "video", fill = "blue")`](https://uci.zoom.us/rec/share/NehdKjr5aFQGIQsvTlUc3zb4wzcC6fHQER0p5fAC0m_UDp21iR5Z1H5l25lF-WNK.ZQLEAQq2TOmICGSM?startTime=1661168845000) [`r fa("file", fill = "blue")`](lecture-slides/lecture7-section7.3-difference-of-two-means.pdf) Section 7.3 Inference for the difference of two means
- Take lecture video quiz 7 due on Canvas Tuesday at noon
